# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5871e50222982c291ff3b35860074a041f6240326293fdca8596d157c4c4338a989586f5acfe416f8398600793cebdeb0744d4846d7a50fea61e182137079a0

test:
  secret_key_base: cbe4425d595ce5c1d4e8fe8782bd15a162b4193698570149c127cc5573e01fe09cfa3758fd1bf10c8f649b3d454e0ac6b9e16b9cc653ce319a3a39f45acfb1ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
